version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/custom_components/fing_ha"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    requirements-files:
      - "manifest.json"