name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "### Description"
  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "Describe the bug here."
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Steps to reproduce the behavior."
      placeholder: "1. Go to '...'\n2. Click on '...'\n3. Scroll down to '...'\n4. See error"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Information about your environment."
      placeholder: "- Home Assistant version:\n- Fing-HA version:\n- Operating System:\n- Browser (if applicable):"
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      description: "By submitting this issue, you agree to follow our [Code of Conduct](../../CODE_OF_CONDUCT.md)."
      options:
        - label: "I have searched for similar issues and couldn't find any."
          required: true
        - label: "I have provided clear and concise reproduction steps."
          required: true
        - label: "I have included relevant environment details."
          required: true