name: Configuration issue
description: Report issues with configuration
title: "[Config]: "
labels: ["config"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "### Configuration Issue"
  - type: textarea
    id: description
    attributes:
      label: "Describe the configuration issue"
      description: "A clear and concise description of the configuration problem."
      placeholder: "Describe the issue here."
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: "Current Configuration"
      description: "Paste your current configuration here."
      placeholder: "configuration.yaml or relevant config..."
      render: yaml
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Steps to reproduce the configuration issue."
      placeholder: "1. Set up config as '...'\n2. Restart HA\n3. See error"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Information about your environment."
      placeholder: "- Home Assistant version:\n- Fing-HA version:\n- Operating System:"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: "Relevant logs or error messages."
      placeholder: "Paste logs here."
      render: shell
  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      description: "By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md)."
      options:
        - label: "I have searched for similar issues and couldn't find any."
          required: true
        - label: "I have provided my configuration."
          required: true
        - label: "I have included relevant logs."
          required: true