blueprint:
  name: "Fing HA: Device Offline Alert"
  description: "Send an alert when an important device goes offline"
  domain: automation
  input:
    device_sensor:
      name: "Device Online Sensor"
      description: "The binary sensor that tracks if the device is online"
      selector:
        entity:
          domain: binary_sensor
          device_class: connectivity
    notification_target:
      name: "Notification Target"
      description: "Who should receive the alert"
      selector:
        target:
          entity:
            domain: notify
    message:
      name: "Alert Message"
      description: "Message to send when device goes offline"
      default: "Device '{{ trigger.to_state.attributes.friendly_name }}' has gone offline"
      selector:
        text:
    title:
      name: "Alert Title"
      description: "Title for the alert"
      default: "Device Offline Alert"
      selector:
        text:
    delay_minutes:
      name: "Delay Before Alert"
      description: "Minutes to wait before sending alert (to avoid false positives)"
      default: 5
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: minutes

mode: single

trigger:
  platform: state
  entity_id: !input device_sensor
  to: "off"
  for:
    minutes: !input delay_minutes

condition:
  - condition: template
    value_template: "{{ trigger.from_state.state == 'on' }}"

action:
  - service: notify.notify
    target: !input notification_target
    data:
      title: !input title
      message: !input message